### ISSUE TITLE
Request for sharing models

### ISSUE THREAD

**Issue by hbin0701** [cxcscmu/MATES#1]
Dear Authors,
Thank you for sharing your work and code :)
Would it be possible for you to also upload the models (i.e. influence models & model checkpoints at each 10k timesteps) to huggingface? It would be really helpful for gaining more insights from your work..!

Thank you in advance :)

**Comment by yuzc19** [comment]
@hbin0701 Hi, thanks for your interest and reasonable request.

I have updated README to add model checkpoint links.

I shared those with my own huggingface account. We will migrate those (and larger files) to our group huggingface organization later.

**Comment by hbin0701** [comment]
Thank you! Sharing them have been of a great help! :)
